nelmio_api_doc:
    documentation:
        info:
            title: API do Back-End Test
            description: Documentação interativa da API
            version: 1.0.0
    areas:
        default:
            path_patterns: [ ^/api ] 
