services:
    # Serviço específico para o Authenticator
    App\Security\ApiKeyAuthenticator:
        arguments:
            $apiKey: '%env(API_KEY)%'

    # Configuração padrão
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    # Registro automático de classes do src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
